openapi: '3.0.0'
info:
  title: Profile APIs
  version: '1.0.0'

paths:
  /api/profile/{userId}:
    put:
      summary: Edit user profile
      description: Edit user profile
      tags:
        - Profile
      securityDefinitions:
        bearerAuth:
          type: apiKey
          in: header
          name: authorization
          description: Authorization token of the user

      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                bio:
                  type: string
                college:
                  type: string
                academicYear:
                  type: string
                branch:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Returns success of edit profile

  /api/profile/all:
    get:
      summary: Fetch all user profiles
      description: Fetch all user profiles
      tags:
        - Profile
      requestBody:
        required: true
        content:
          application/json:
      responses:
        '200':
          description: Fetched all profiles successfully

  /api/profile/single/{userId}:
    get:
      summary: Fetch user profile
      description: Fetch user profile
      tags:
        - Profile
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
      responses:
        '200':
          description: Returns fetched profile

  /api/profile/custom:
    get:
      summary: Get profile suggestions
      description: Get profile suggestions
      tags:
        - Profile
      securityDefinitions:
        bearerAuth:
          type: apiKey
          in: header
          name: authorization
          description: Authorization token of the user

      security:
        - bearerAuth: []
      responses:
        '200':
          description: Returns fetched profiles

  /api/profilePicture:
    put:
      summary: Edit profile image
      description: Edit profile image
      tags:
        - Profile
      securityDefinitions:
        bearerAuth:
          type: apiKey
          in: header
          name: authorization
          description: Authorization token of the user

      security:
        - bearerAuth: []
      consumes:
        - multipart/form-data
      produces:
        - application/json
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                profilePicture:
                  type: file
                  format: binary
              required:
                - profilePicture
      responses:
        "200":
          description: Returns success of updated profile image

  /api/coverImage:
    put:
      summary: Edit cover image
      description: Edit cover image
      tags:
        - Profile
      securityDefinitions:
        bearerAuth:
          type: apiKey
          in: header
          name: authorization
          description: Authorization token of the user

      security:
        - bearerAuth: []
      consumes:
        - multipart/form-data
      produces:
        - application/json
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                coverImage:
                  type: file
                  format: binary
              required:
                - coverImage
      responses:
        "200":
          description: Returns success of updated cover image
