openapi: '3.0.0'
info:
  title: Authentication APIs
  version: '1.0.0'

paths:
  /api/register:
    post:
      summary: Register User
      description: Register User
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Returns success of user registration

  /api/login:
    post:
      summary: Login user
      description: Login user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Returns success of login and user details

  /api/google/login:
    post:
      summary: Google login
      description: Google login
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                email:
                  type: string
                token:
                  type: string
      responses:
        '200':
          description: Returns success of google login
